# Generated by Django 4.2.4 on 2023-08-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('bolsa', models.CharField(max_length=40)),
                ('stock', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='stock_limpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('envase', models.CharField(max_length=40)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo', models.IntegerField()),
                ('uala', models.IntegerField()),
                ('mercado_pago', models.IntegerField()),
                ('banco_provincia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_veneno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('envase', models.CharField(max_length=40)),
                ('stock', models.CharField(max_length=40)),
            ],
        ),
    ]
